# Site settings
name: sdlyyxy
email: sdlyyxy@icloud.com
author: sdlyyxy
url: https://sdlyyxy.github.io
resume_site: https://sdlyyxy.github.io # in header “关于作者”
github: https://github.com/sdlyyxy/ # no use in the present
baseurl: ""
description: 天朗气清　惠风和畅
meta_description: sdlyyxy # used in html's head , meta, description 
motto: 天朗气清　惠风和畅
banner: 天朗气清　惠风和畅
language: zh-Hans
timezone: Asia/Shanghai

#permalink: /:categories/:year/:month/:day/:title/
url: "http://blog.sdlyyxy.com/"
permalink: /:year/:month/:day/:title/
plugins: 
    - jekyll-paginate
    - jekyll-feed
#    - jekyll-github-metadata
    - jekyll-sitemap
paginate: 10

feed:
  path: atom.xml

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile','vendor/']

github_username: sdlyyxy
highlighter: rouge

# Build settings
markdown: kramdown
kramdown:
    input: GFM

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

# FB:
#   comments :
#     provider : duoshuo
#     duoshuo:
#         short_name : luoyan35714
#     disqus :
#         short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
