# Site settings
name: sdlyyxy's blog
email: sdlyyxy@icloud.com
author: sdlyyxy
url: https://sdlyyxy.github.io
resume_site: https://sdlyyxy.github.io
github: https://github.com/sdlyyxy/
baseurl: ""
description: Actually, less is more!
meta_description: description 
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
gems: [jekyll-paginate]
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: sdlyyxy
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
